"""empty message

Revision ID: 85fcdb2fc125
Revises: 
Create Date: 2019-03-05 02:12:22.946658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fcdb2fc125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pembeli', sa.Column('address', sa.String(length=500), nullable=False))
    op.add_column('Pembeli', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('Produk', sa.Column('deskripsi_produk', sa.Text(), nullable=False))
    op.add_column('Produk', sa.Column('foto_produk', sa.String(length=500), nullable=False))
    op.add_column('Produk', sa.Column('kategori', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Produk', 'kategori')
    op.drop_column('Produk', 'foto_produk')
    op.drop_column('Produk', 'deskripsi_produk')
    op.drop_column('Pembeli', 'email')
    op.drop_column('Pembeli', 'address')
    # ### end Alembic commands ###
